### ISSUE TITLE
Missing talent data

### ISSUE THREAD

**Issue by scamille** [Bloodmallet/simc_support#5]
```
from simc_support.game_data import WowSpec
spec = WowSpec.get_wow_spec_from_combined_simc_name("Priest_Shadow")
print(spec.talents[2])
```
returns
```
{3: {'name': 'Intangibility', 'spell_id': 288733}, 2: {'name': "San'layn", 'spell_id': 199855}}
```

This seems to be missing talent with key 1, namely "Body and Soul"

Edit:
```
from simc_support.game_data import WowSpec
for spec in WowSpec.WOWSPECS:
  for i in range(1, 7):
    for j in range(1, 3):
      try:
        talent = spec.talents[i+1][j]
      except Exception as e:
        print(f"Error obtaining talent for spec {spec} at row {i} with talent# {j}")
```
Results in a ton of missing talents.

**Comment by Bloodmallet** [comment]
Thank you for the issue. I'll check that out and will write a unittest to catch those early in the future. And of course I'll check what happened there.

**Comment by Bloodmallet** [comment]
Seems like there are quite a lot of talents missing somehow. 🤔 Digging further. Somehow I'm missing 184 talents.

**Comment by scamille** [comment]
Yes, see my script in the edited post up there to list them all. I guess that would make a good unit test for this as well :)

**Comment by Bloodmallet** [comment]
```python
    def test_existance_of_all(self):
        for wow_spec in WOWSPECS:
            talents = get_talent_dict(wow_spec)
            for row in range(1, 8):
                for column in range(1, 4):
                    with self.subTest(
                        wow_spec=wow_spec, talents=talents, row=row, column=column
                    ):
                        self.assertTrue(
                            row in talents,
                            f"Talent row {row} for {wow_spec} was not found.",
                        )
                        self.assertTrue(
                            column in talents[row],
                            f"Talent {column} in row {row} for {wow_spec} was not found.",
                        )
``` 
This is my current new unittest to retest it in the future.

**Comment by Bloodmallet** [comment]
Somehow I'm not seeing some talents in those extractions. This can be seen here, too: https://wow.tools/dbc/?dbc=talent&build=9.0.2.36165#page=1&colFilter[2]=3&colFilter[6]=73

**Comment by Bloodmallet** [comment]
Navv informed me about non-spec specific talents. Which I accidentally filtered out all the time. Fixing. This should take care of the current problem.

**Comment by Bloodmallet** [comment]
A new version was published, that fixes this issue.  https://pypi.org/project/simc-support/9.0.2.1a6/
