### ISSUE TITLE
Some healing specs are missing from WowSpec.py

### ISSUE THREAD

**Issue by Melekus** [Bloodmallet/simc_support#9]
Mistweaver Monk and Holy Paladin are not defined in WowSpec.py, resulting in errors when running simc CI tests such as https://github.com/simulationcraft/simc/pull/5913/checks?check_run_id=2475012544

**Comment by Bloodmallet** [comment]
Thank you for the issue. I'll look into that soon.

**Comment by scamille** [comment]
#10

**Comment by Bloodmallet** [comment]
@scamille thank you for the PR. 
- Holy pladin requires intellect as its primary stats and 
- mistweaver monk is not yet in it. 

Do you want to update the PR?

**Comment by abelito75** [comment]
Since PR 11 was merged does that means this issue is completed? (Just trying to follow up since I'm the reason why Melekus might have created the issue)

**Comment by Bloodmallet** [comment]
The baseline should be present. Let me know if your usecase is working. Some data (like talent names and translations) is still missing and I need to fix some CI stuff that popped up. But I expect the library to function properly for SimulationCrafts own CI setup. I'd like to keep this ticket open until I've been able to fix  my own CI and the missing data for the two new specs.

- CI
- data extraction/update for specs

**Comment by scamille** [comment]
Simc CI is working for holy paladin.
https://github.com/simulationcraft/simc/pull/5913/checks?check_run_id=2500988939

**Comment by Bloodmallet** [comment]
9.1.0 will provide data for the newly added specs.
